# Generated by Django 5.2.9 on 2025-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('verb', models.CharField(choices=[('trip_created', 'Создан маршрут'), ('review_created', 'Создан отзыв'), ('media_added', 'Добавлено медиа'), ('followed', 'Подписался')], max_length=32, verbose_name='Действие')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Кешированный снэпшот: заголовок, короткое описание, ссылки.', verbose_name='Данные события')),
                ('is_recommended', models.BooleanField(default=False, help_text='Помечает событие как подобранное случайно/рекомендованное.', verbose_name='Рекомендовано')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
