# Generated by Django 5.2.9 on 2025-12-16 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название точки')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('radius_meters', models.PositiveIntegerField(blank=True, help_text='Используется для определения пересечений координат.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Радиус действия, м')),
                ('environment', models.CharField(choices=[('city', 'Город'), ('forest', 'Лес'), ('plain', 'Равнина'), ('water', 'Вода')], default='city', help_text='Среда влияет на радиус по умолчанию (город, лес и т.д.).', max_length=16, verbose_name='Среда')),
            ],
            options={
                'verbose_name': 'Точка покрытия',
                'verbose_name_plural': 'Точки покрытия',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geohub_geoc_latitud_73150b_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeoCoverageBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='geohub.geocoverage', verbose_name='Точка покрытия')),
            ],
            options={
                'verbose_name': 'Привязка точки покрытия',
                'verbose_name_plural': 'Привязки точек покрытия',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='geohub_geoc_content_6404ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('coverage', 'content_type', 'object_id'), name='uq_geo_coverage_binding_target')],
            },
        ),
    ]
