# Generated by Django 5.2.9 on 2025-12-18 13:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('code', models.SlugField(help_text='Уникальный код типа, используется на фронтенде и при импорте.', max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('radius_meters_default', models.PositiveIntegerField(default=1000, help_text='Будет подставлен в точку покрытия, если не указан вручную.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Радиус по умолчанию, м')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные типы скрываются из списка.', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип места',
                'verbose_name_plural': 'Типы мест',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GeoCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название точки')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Долгота')),
                ('radius_meters', models.PositiveIntegerField(blank=True, help_text='Используется для определения пересечений координат.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Радиус действия, м')),
                ('place_type', models.ForeignKey(help_text='Определяет радиус по умолчанию и тип среды (город, лес и т.д.).', on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='geohub.placetype', verbose_name='Тип местности')),
            ],
            options={
                'verbose_name': 'Точка покрытия',
                'verbose_name_plural': 'Точки покрытия',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GeoCoverageBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='geohub.geocoverage', verbose_name='Точка покрытия')),
            ],
            options={
                'verbose_name': 'Привязка точки покрытия',
                'verbose_name_plural': 'Привязки точек покрытия',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='geohub_geoc_content_6404ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('coverage', 'content_type', 'object_id'), name='uq_geo_coverage_binding_target')],
            },
        ),
        migrations.AddIndex(
            model_name='geocoverage',
            index=models.Index(fields=['latitude', 'longitude'], name='geohub_geoc_latitud_73150b_idx'),
        ),
    ]
