# Generated by Django 5.2.9 on 2025-12-10 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название прокси')),
                ('proxy_socks', models.CharField(max_length=400, verbose_name='прокси полный socks')),
                ('proxy_http', models.CharField(max_length=400, verbose_name='прокси полный http')),
                ('proxy_url', models.CharField(max_length=200, verbose_name='прокси формата http://proxy_host:proxy_port')),
                ('proxy_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='прокси username')),
                ('proxy_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='прокси password')),
            ],
            options={
                'verbose_name': 'прокси для соединения',
                'verbose_name_plural': 'прокси для соединения',
            },
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28, verbose_name='название промпта')),
                ('prompt_text', models.TextField(verbose_name='текст промпта')),
                ('ru_prompt_text', models.TextField(verbose_name='текст промпта на русском')),
                ('is_default', models.BooleanField(default=False, verbose_name='по умолчанию')),
                ('consumer', models.CharField(choices=[('FCH', 'чат'), ('REM', 'системный'), ('IMG', 'картинка')], default='FCH', max_length=3, verbose_name='потребитель запроса')),
            ],
            options={
                'verbose_name': 'промпт для GPT',
                'verbose_name_plural': 'промпты для GPT',
            },
        ),
        migrations.CreateModel(
            name='GptModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_cdk', models.CharField(choices=[('OA', 'open Ai'), ('AP', 'anthropic')], default='OA', max_length=2, verbose_name='провайдер CDK')),
                ('public_name', models.CharField(max_length=70, verbose_name='название модели')),
                ('title', models.CharField(max_length=28, verbose_name='модель GPT')),
                ('base_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='base_url')),
                ('is_default', models.BooleanField(default=False, verbose_name='доступна всем по умолчанию')),
                ('is_free', models.BooleanField(default=False, verbose_name='бесплатная для пользователя')),
                ('incoming_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='стоимость входящих / 100K токенов')),
                ('outgoing_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='стоимость исходящих / 100K токенов')),
                ('token', models.CharField(max_length=200, verbose_name='токен для запроса')),
                ('context_window', models.IntegerField(verbose_name='окно количества токенов для передачи истории в запросе')),
                ('max_request_token', models.IntegerField(verbose_name='максимальное количество токенов в запросе')),
                ('time_window', models.IntegerField(default=30, verbose_name='окно времени для передачи истории в запросе, мин')),
                ('consumer', models.CharField(choices=[('FCH', 'чат'), ('REM', 'системный'), ('IMG', 'картинка')], default='FCH', max_length=3, verbose_name='потребитель запроса')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_proxy', to='ai.proxy')),
            ],
            options={
                'verbose_name': 'модель GPT',
                'verbose_name_plural': 'модели GPT',
            },
        ),
        migrations.CreateModel(
            name='TextTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('room_group_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='WEB чат')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('question_tokens', models.PositiveIntegerField(null=True)),
                ('question_token_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='стоимость исходящих / 100K токенов')),
                ('image_url', models.CharField(blank=True, max_length=1280, null=True, verbose_name='url картинки для анализа')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_tokens', models.PositiveIntegerField(null=True)),
                ('answer_token_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='стоимость входящих / 100K токенов')),
                ('consumer', models.CharField(choices=[('FCH', 'чат'), ('REM', 'системный'), ('IMG', 'картинка')], default='FCH', max_length=3, verbose_name='потребитель запроса')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_ai', to='ai.gptmodels')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_ai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История запросов к ИИ',
                'verbose_name_plural': 'История запросов к ИИ',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='UploadedScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_id', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='scan/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGptModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала окна для передачи истории')),
                ('active_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='ai.gptmodels', verbose_name='активная модель')),
                ('approved_models', models.ManyToManyField(related_name='approved_users', to='ai.gptmodels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_models', to=settings.AUTH_USER_MODEL)),
                ('active_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_user', to='ai.userprompt', verbose_name='активный промпт')),
            ],
            options={
                'verbose_name': 'разрешенная GPT модели юзера',
                'verbose_name_plural': 'разрешенные GPT модели юзера',
            },
        ),
    ]
