# Generated by Django 5.2.9 on 2025-12-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='texttransactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_ai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedscanimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergptmodels',
            name='active_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='ai.gptmodels', verbose_name='активная модель'),
        ),
        migrations.AddField(
            model_name='usergptmodels',
            name='approved_models',
            field=models.ManyToManyField(related_name='approved_users', to='ai.gptmodels'),
        ),
        migrations.AddField(
            model_name='usergptmodels',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergptmodels',
            name='active_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_user', to='ai.userprompt', verbose_name='активный промпт'),
        ),
    ]
