# Generated by Django 5.2.9 on 2025-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('is_active', models.BooleanField(default=True, help_text='Можно скрыть место без удаления.', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('name',),
            },
        ),
    ]
