# Generated by Django 5.2.9 on 2025-12-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geohub', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Только автор может редактировать место.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(blank=True, help_text='Выбирается из справочника типов мест.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='geohub.placetype', verbose_name='Тип места'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['country', 'region', 'city'], name='places_plac_country_57484c_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_type', 'is_active'], name='places_plac_place_t_67d886_idx'),
        ),
    ]
