# Generated by Django 5.2.9 on 2025-12-08 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Needed for moderation and ownership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placemedia',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='places.place'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['country', 'region', 'city'], name='places_plac_country_57484c_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='places_plac_latitud_09f61a_idx'),
        ),
    ]
