# Generated by Django 5.2.9 on 2025-12-16 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemedia',
            name='place',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',), 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_latitud_09f61a_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='main_photo',
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Используется для модерации и владения.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Можно скрыть место без удаления.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('beach', 'Пляж'), ('city', 'Город'), ('sight', 'Достопримечательность'), ('trek', 'Маршрут/трекинг'), ('park', 'Парк'), ('museum', 'Музей'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_type', 'is_active'], name='places_plac_place_t_0c1a6a_idx'),
        ),
        migrations.DeleteModel(
            name='PlaceMedia',
        ),
    ]
