# Generated by Django 5.2.9 on 2025-12-09 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID файла')),
                ('key', models.CharField(db_index=True, help_text='Ключ (путь) к файлу в бакете MediaStorage.', max_length=1024, verbose_name='Путь в хранилище')),
                ('original_name', models.CharField(blank=True, help_text='Имя файла при загрузке пользователем.', max_length=255, verbose_name='Исходное имя файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ'), ('audio', 'Аудио'), ('other', 'Другое')], db_index=True, default='other', help_text='Логический тип файла: изображение, видео, документ и т.д.', max_length=16, verbose_name='Тип файла')),
                ('content_type', models.CharField(blank=True, help_text='MIME-тип файла (например, image/webp, application/pdf).', max_length=100, verbose_name='MIME-тип')),
                ('extension', models.CharField(blank=True, help_text='Расширение файла без точки, например: jpg, webp, pdf.', max_length=16, verbose_name='Расширение')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла, байт')),
                ('visibility', models.CharField(choices=[('private', 'Только владелец'), ('auth', 'Все авторизованные пользователи'), ('public', 'Доступен всем')], db_index=True, default='private', help_text='Кто может обращаться к файлу.', max_length=16, verbose_name='Уровень доступа')),
                ('checksum', models.CharField(blank=True, help_text='Например, SHA256 для проверки целостности и дедупликации.', max_length=128, verbose_name='Хэш файла')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Произвольные служебные данные о файле (EXIF, длительность и т.п.).', verbose_name='Дополнительные метаданные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает загрузки'), ('uploaded', 'Загружен в хранилище'), ('processing', 'Обрабатывается'), ('ready', 'Готов к использованию'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус файла')),
                ('error_code', models.CharField(blank=True, choices=[('', 'Нет ошибки'), ('forbidden_extension', 'Запрещённое расширение файла'), ('bad_extension', 'Недопустимое расширение файла'), ('bad_mime', 'Недопустимый MIME-тип файла'), ('too_large', 'Слишком большой файл'), ('infected', 'Файл заражён (антивирус)'), ('corrupted', 'Файл повреждён или не распознан'), ('processing_error', 'Внутренняя ошибка обработки файла')], default='', help_text='Машинный код ошибки валидации или обработки файла.', max_length=64, verbose_name='Код ошибки')),
                ('error_detail', models.TextField(blank=True, help_text='Человекочитаемое описание ошибки (для логов и отладки).', verbose_name='Описание ошибки')),
                ('owner', models.ForeignKey(blank=True, help_text='Пользователь, загрузивший файл. Может быть пустым для системных файлов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец файла')),
            ],
            options={
                'verbose_name': 'Медиа-файл',
                'verbose_name_plural': 'Медиа-файлы',
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID привязки')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID связанного объекта')),
                ('role', models.CharField(choices=[('main', 'Главное медиа'), ('gallery', 'Галерея'), ('document', 'Документ'), ('avatar', 'Аватар'), ('other', 'Другое')], db_index=True, default='other', help_text='Назначение файла: главное фото, документ, аватар и т.д.', max_length=32, verbose_name='Роль медиа')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Чем меньше число, тем выше приоритет отображения.', verbose_name='Приоритет')),
                ('is_primary', models.BooleanField(default=False, help_text='Если отмечен, считается главным в рамках данной роли и объекта.', verbose_name='Главный файл в роли')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип связанной модели')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='filehub.mediafile', verbose_name='Медиа-файл')),
            ],
            options={
                'verbose_name': 'Привязка медиа-файла',
                'verbose_name_plural': 'Привязки медиа-файлов',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFileVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID варианта')),
                ('kind', models.CharField(choices=[('original', 'Оригинал'), ('webp', 'WebP-версия'), ('thumb_large', 'Крупный превью (800x800)'), ('thumb_small', 'Малый превью (300x300)'), ('preview_base64', 'Мини-превью в Base64')], max_length=32, verbose_name='Тип варианта')),
                ('key', models.CharField(db_index=True, help_text='Ключ (путь) варианта файла в бакете MediaStorage.', max_length=1024, verbose_name='Путь варианта в хранилище')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина, px')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота, px')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер варианта, байт')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип варианта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает загрузки'), ('uploaded', 'Загружен в хранилище'), ('processing', 'Обрабатывается'), ('ready', 'Готов к использованию'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус обработки')),
                ('error_code', models.CharField(blank=True, choices=[('', 'Нет ошибки'), ('forbidden_extension', 'Запрещённое расширение файла'), ('bad_extension', 'Недопустимое расширение файла'), ('bad_mime', 'Недопустимый MIME-тип файла'), ('too_large', 'Слишком большой файл'), ('infected', 'Файл заражён (антивирус)'), ('corrupted', 'Файл повреждён или не распознан'), ('processing_error', 'Внутренняя ошибка обработки файла')], default='', max_length=64, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='filehub.mediafile', verbose_name='Исходный файл')),
            ],
            options={
                'verbose_name': 'Вариант медиа-файла',
                'verbose_name_plural': 'Варианты медиа-файлов',
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['owner', 'file_type'], name='mediafile_owner_type_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['key'], name='mediafile_key_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['status'], name='mediafile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='media_attach_ct_obj_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id', 'role'), name='uniq_primary_media_per_object_and_role'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaattachment',
            unique_together={('content_type', 'object_id', 'media_file', 'role')},
        ),
        migrations.AddIndex(
            model_name='mediafilevariant',
            index=models.Index(fields=['media_file', 'kind'], name='media_variant_media_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafilevariant',
            index=models.Index(fields=['key'], name='media_variant_key_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafilevariant',
            unique_together={('media_file', 'kind')},
        ),
    ]
