# Generated by Django 5.2.9 on 2025-12-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filehub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Пользователь, загрузивший файл. Может быть пустым для системных файлов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец файла'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='filehub.mediafile', verbose_name='Медиа-файл'),
        ),
        migrations.AddField(
            model_name='mediafilevariant',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='filehub.mediafile', verbose_name='Исходный файл'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['owner', 'file_type'], name='mediafile_owner_type_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['key'], name='mediafile_key_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['status'], name='mediafile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='media_attach_ct_obj_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id', 'role'), name='uniq_primary_media_per_object_and_role'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaattachment',
            unique_together={('content_type', 'object_id', 'media_file', 'role')},
        ),
        migrations.AddIndex(
            model_name='mediafilevariant',
            index=models.Index(fields=['media_file', 'kind'], name='media_variant_media_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafilevariant',
            index=models.Index(fields=['key'], name='media_variant_key_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafilevariant',
            unique_together={('media_file', 'kind')},
        ),
    ]
