# Generated by Django 5.2.9 on 2025-12-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source_trip',
            field=models.ForeignKey(blank=True, help_text="Для копий 'Сохранить себе' сохраняем ссылку на оригинал.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='trips.trip', verbose_name='Исходный маршрут'),
        ),
        migrations.AddField(
            model_name='trippoint',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Связь с Place, если точка основана на существующем месте.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_points', to='places.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='trippoint',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='trips.trip', verbose_name='Маршрут'),
        ),
    ]
