# Generated by Django 5.2.9 on 2025-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('reason', models.TextField(verbose_name='Причина/текст жалобы')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('resolved', 'Решена'), ('dismissed', 'Отклонена')], default='open', max_length=16, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта в')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Опционально: зафиксировать краткие данные о целевом объекте на момент жалобы.', verbose_name='Снэпшот объекта')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
