# Generated by Django 5.2.9 on 2025-12-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['content_type', 'object_id'], name='complaints__content_a52642_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['author', 'created_at'], name='complaints__author__513901_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='complaints__status_39c2ad_idx'),
        ),
    ]
